Repository Teemo-Wanted/SNS_Feed_Service, pull requests merged in 2023-11, with the labels that each got.

#24 [Feat] 게시물 좋아요, 공유하기 API 구현
  build.gradle
  src/main/java/com/wanted/sns_feed_service/feed/FeedService.java
  src/main/java/com/wanted/sns_feed_service/feed/WebClientService.java
  src/main/java/com/wanted/sns_feed_service/feed/controller/FeedController.java
  src/main/java/com/wanted/sns_feed_service/feed/entity/Feed.java
  src/main/java/com/wanted/sns_feed_service/feed/entity/Type.java
Labels: enhancement

#26 [Fix] 이메일 인증 버그 수정
  src/main/java/com/wanted/sns_feed_service/initData/NotProd.java
  src/main/java/com/wanted/sns_feed_service/member/controller/MemberController.java
  src/main/java/com/wanted/sns_feed_service/member/repository/MemberRepository.java
  src/main/java/com/wanted/sns_feed_service/member/service/MemberService.java
  src/test/java/com/wanted/sns_feed_service/member/controller/MemberControllerTests.java
Labels: bug

#30 [Feat] authorization interceptor
  src/main/java/com/wanted/sns_feed_service/config/MvcConfig.java
  src/main/java/com/wanted/sns_feed_service/interceptor/AuthorizationInterceptor.java
  src/main/java/com/wanted/sns_feed_service/interceptor/AuthorizationTestController.java
  src/main/java/com/wanted/sns_feed_service/resolver/LoginMember.java
  src/main/java/com/wanted/sns_feed_service/resolver/LoginMemberContext.java
  src/main/java/com/wanted/sns_feed_service/resolver/LoginUser.java
  src/main/java/com/wanted/sns_feed_service/resolver/LoginUserResolver.java
Labels: enhancement

#32 [Docs] Swagger 문서 및 권한이 필요한 인터셉터 예외처리
  src/main/java/com/wanted/sns_feed_service/config/MvcConfig.java
  src/main/java/com/wanted/sns_feed_service/config/SwaggerConfig.java
  src/main/java/com/wanted/sns_feed_service/exceptionHandler/ApiGlobalExceptionHandler.java
  src/main/java/com/wanted/sns_feed_service/exceptionHandler/AuthenticationException.java
  src/main/java/com/wanted/sns_feed_service/feed/controller/FeedController.java
  src/main/java/com/wanted/sns_feed_service/initData/NotProd.java
  src/main/java/com/wanted/sns_feed_service/interceptor/AuthorizationInterceptor.java
  src/main/java/com/wanted/sns_feed_service/interceptor/AuthorizationTestController.java
  src/test/java/com/wanted/sns_feed_service/feed/controller/FeedControllerTest.java
  src/test/java/com/wanted/sns_feed_service/member/controller/MemberControllerTests.java
Labels: documentation
